import { describe, expect, it } from 'vitest'
import { crc16Kermit } from './crc16'
import { CH_CMS, CH_LOG, CH_SAS, MuxParser, muxFrame } from './muxCodec'

function referenceFrame(chan: number, payload: Buffer): Buffer {
  // Mirror of tools/host_sim/mux.py frame(): SYNC + chan + len16 LE + payload + crc16 LE
  const body = Buffer.concat([Buffer.from([chan, payload.length & 0xff, payload.length >> 8]), payload])
  const crc = crc16Kermit(body)
  return Buffer.concat([Buffer.from([0x7e]), body, Buffer.from([crc & 0xff, crc >> 8])])
}

describe('mux framing', () => {
  it('matches golden frames generated by tools/host_sim/mux.py', () => {
    // python3 -c "from mux import frame; print(frame(0x01, bytes([0x81])).hex())"
    expect(muxFrame(CH_SAS, Buffer.from([0x81])).toString('hex')).toBe('7e01010081e6d3')
    expect(muxFrame(CH_CMS, Buffer.from('hello cms', 'ascii')).toString('hex'))
      .toBe('7e02090068656c6c6f20636d732e58')
  })

  it('builds frames identical to the Python reference construction', () => {
    const payload = Buffer.from([0x81])
    expect(muxFrame(CH_SAS, payload)).toEqual(referenceFrame(CH_SAS, payload))
    const big = Buffer.alloc(300, 0xab)
    expect(muxFrame(CH_CMS, big)).toEqual(referenceFrame(CH_CMS, big))
  })

  it('rejects oversized payloads', () => {
    expect(() => muxFrame(CH_SAS, Buffer.alloc(2049))).toThrow()
  })

  it('parses whole frames', () => {
    const parser = new MuxParser()
    const frames = parser.feed(muxFrame(CH_SAS, Buffer.from([0x81])))
    expect(frames).toEqual([{ chan: CH_SAS, payload: Buffer.from([0x81]) }])
  })

  it('parses frames arriving in arbitrary chunks', () => {
    const parser = new MuxParser()
    const wire = Buffer.concat([
      muxFrame(CH_SAS, Buffer.from([0x01, 0x1a])),
      muxFrame(CH_LOG, Buffer.from('hello', 'ascii'))
    ])
    const collected: { chan: number; payload: Buffer }[] = []
    for (const byte of wire) {
      collected.push(...parser.feed(Buffer.from([byte])))
    }
    expect(collected).toHaveLength(2)
    expect(collected[0].chan).toBe(CH_SAS)
    expect(collected[1].chan).toBe(CH_LOG)
    expect(collected[1].payload.toString('ascii')).toBe('hello')
  })

  it('resyncs past garbage and boot noise', () => {
    const parser = new MuxParser()
    const wire = Buffer.concat([
      Buffer.from('ets Jul 29 2019 boot rom garbage \x7e\x99\xff', 'latin1'),
      muxFrame(CH_SAS, Buffer.from([0x81]))
    ])
    const frames = parser.feed(wire)
    expect(frames).toEqual([{ chan: CH_SAS, payload: Buffer.from([0x81]) }])
  })

  it('drops frames with bad CRC and recovers on the next frame', () => {
    const parser = new MuxParser()
    const corrupted = muxFrame(CH_SAS, Buffer.from([0x81]))
    corrupted[corrupted.length - 1] ^= 0xff
    const frames = parser.feed(Buffer.concat([corrupted, muxFrame(CH_SAS, Buffer.from([0x80]))]))
    expect(frames).toEqual([{ chan: CH_SAS, payload: Buffer.from([0x80]) }])
  })

  it('rejects invalid channels by resyncing', () => {
    const parser = new MuxParser()
    const bogus = referenceFrame(0x55, Buffer.from([0x01]))
    const frames = parser.feed(Buffer.concat([bogus, muxFrame(CH_SAS, Buffer.from([0x81]))]))
    expect(frames).toEqual([{ chan: CH_SAS, payload: Buffer.from([0x81]) }])
  })
})
